### ISSUE TITLE
Dashboard UI not displaying properly on chrome browser unlike in safari

### ISSUE THREAD

**Issue by valmayaki** [andela/bp-esa-frontend#33]
![screen shot 2019-02-12 at 3 57 07 pm](https://user-images.githubusercontent.com/8375520/52644423-123bbb80-2edf-11e9-9d9f-5bc315ae808b.png)
<img width="744" alt="screen shot 2019-02-12 at 3 54 26 pm" src="https://user-images.githubusercontent.com/8375520/52644434-17006f80-2edf-11e9-8115-bf7a97b96e3a.png">
You will notice in the images above that the nav top bar displays differently in chrome than in safari

**Comment by matthewacha** [comment]
this has been fixed
